# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, verbose_name='品牌名称')),
                ('telephone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('brand_web', models.CharField(max_length=100, verbose_name='官方网站')),
                ('brand_logo', models.ImageField(upload_to='image/logo/%Y', verbose_name='品牌logo')),
                ('brand_desc', models.CharField(max_length=200, verbose_name='品牌描述')),
                ('brand_status', models.CharField(choices=[('enable', '启用'), ('disable', '禁用')], default='enable', max_length=10, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '产品品牌',
                'verbose_name_plural': '产品品牌',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('add_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='添加时的价格')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('category_code', models.CharField(max_length=30, unique=True, verbose_name='分类编码')),
                ('image', models.ImageField(default='', upload_to='image/CategoryImage/%Y/%m', verbose_name='类别图片')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, verbose_name='编码')),
                ('product_name', models.CharField(max_length=50, verbose_name='名称')),
                ('subTitle', models.CharField(max_length=50, verbose_name='小标题')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='原始价格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='促销价格')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='进货成本')),
                ('publish_status', models.CharField(choices=[('up', '上架'), ('down', '下架')], default='down', max_length=5, verbose_name='上下架状态')),
                ('description', models.CharField(default='', max_length=100, verbose_name='描述')),
                ('stock', models.IntegerField(default=0, verbose_name='库存量')),
                ('monthlyVolume', models.IntegerField(default=0, verbose_name='月成交量')),
                ('commentNum', models.IntegerField(default=0, verbose_name='评论数')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('is_freeShipping', models.BooleanField(default=False, verbose_name='是否包邮')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.BrandInfo', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category', verbose_name='类别')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '产品图片'), ('detailImage', '详情图片')], max_length=11, verbose_name='类型')),
                ('image', models.ImageField(upload_to='image/productImage/%Y/%m/%d', verbose_name='图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='products.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='属性名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertys', to='products.Category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '产品属性',
                'verbose_name_plural': '产品属性',
            },
        ),
        migrations.CreateModel(
            name='Propertyvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='属性值')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyValues', to='products.Product', verbose_name='所属产品')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyValues', to='products.Property', verbose_name='属性值')),
            ],
            options={
                'verbose_name': '属性值',
                'verbose_name_plural': '属性值',
            },
        ),
    ]
