# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, verbose_name='品牌名称')),
                ('telephone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('brand_web', models.CharField(max_length=100, verbose_name='官方网站')),
                ('brand_logo', models.ImageField(upload_to='image/logo/%Y', verbose_name='品牌logo')),
                ('brand_desc', models.CharField(max_length=200, verbose_name='品牌描述')),
                ('brand_status', models.CharField(choices=[('enable', '启用'), ('disable', '禁用')], default='enable', max_length=10, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.Category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '产品品牌',
                'verbose_name_plural': '产品品牌',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Brand', verbose_name='品牌'),
        ),
        migrations.DeleteModel(
            name='BrandInfo',
        ),
    ]
