# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='手机号码')),
                ('zip', models.CharField(max_length=10, verbose_name='邮政编码')),
                ('province', models.CharField(max_length=30, verbose_name='省（市区）')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('town', models.CharField(default='', max_length=30, verbose_name='区域')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=30, verbose_name='订单编号')),
                ('receiver', models.CharField(blank=True, max_length=50, null=True, verbose_name='收货人姓名')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='收货地址')),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('payment_method', models.CharField(blank=True, choices=[('1', '现金'), ('2', '余额'), ('3', '网银'), ('4', '支付宝'), ('5', '微信')], max_length=3, null=True, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='优惠金额')),
                ('payment_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('courier_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='运费')),
                ('courier_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司')),
                ('courier_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='快递单号')),
                ('order_status', models.CharField(choices=[('1', '待付款'), ('2', '待发货'), ('3', '待收货'), ('4', '待评价'), ('5', '已完成')], default=1, max_length=3, verbose_name='订单状态')),
                ('order_point', models.IntegerField(default=0, verbose_name='订单积分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('product_num', models.IntegerField(default=1, verbose_name='数量')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('1', '订单积分'), ('2', '活动积分'), ('3', '消费')], max_length=4, verbose_name='来源或去向')),
                ('order_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源或去向所属的订单编号')),
                ('change_point', models.IntegerField(verbose_name='变更积分数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '积分变更日志',
                'verbose_name_plural': '积分变更日志',
            },
        ),
    ]
