# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20170709_0105'),
        ('orders', '0011_auto_20170709_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('packing', models.CharField(choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], default='0', max_length=3, verbose_name='商品包装')),
                ('deliverySpeed', models.CharField(choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], default='0', max_length=3, verbose_name='送货速度')),
                ('deliveryClerkServices', models.CharField(choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], default='0', max_length=3, verbose_name='配送员服务态度')),
                ('SellerServices', models.CharField(choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分')], default='0', max_length=3, verbose_name='卖家服务')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='是否匿名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.OrderItem', verbose_name='所属订单项')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product', verbose_name='所属产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
