# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCode', models.CharField(max_length=10, verbose_name='公司编码')),
                ('companyName', models.CharField(max_length=50, verbose_name='公司名称')),
                ('contact', models.CharField(max_length=50, verbose_name='公司联系人')),
                ('telphone', models.CharField(max_length=100, verbose_name='联系电话')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='配送单价')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '物流公司',
                'verbose_name_plural': '物流公司',
            },
        ),
        migrations.CreateModel(
            name='TmallShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flagshipShop', '旗舰店'), ('ExclusiveShop', '专卖店'), ('FranchisedStore', '专营店')], max_length=30, verbose_name='商铺类型')),
                ('shopName', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('companyInfo', models.TextField(verbose_name='公司信息')),
                ('scope', models.TextField(verbose_name='经营范围')),
                ('location', models.CharField(max_length=200, verbose_name='所在地')),
                ('BusinessLicense', models.ImageField(upload_to='image/BusinessLicense/%Y/%m', verbose_name='工商执照')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '天猫商铺',
                'verbose_name_plural': '天猫商铺',
            },
        ),
    ]
